### ISSUE TITLE
CRA2 unexpected token (html tag)

### ISSUE THREAD

**Issue by pawelkrystkiewicz** [limistah/react-here-map#2]
Hi! Great idea for Here Maps library in React. I love it!
I have a problem though.

**Steps to reproduce:**
1. `create-react-app map-test`
2. `yarn add react-here-maps`
3. Copy example from the readme
4. Add your own `APP_ID` and `APP_KEY`
5. `yarn start`

**Outcome:**

> `UNEXPECTED TOKEN`
> ...\node_modules\react-here-map\src\components\HMap\index.js: Unexpected token (27:11)
>   25 |   }
>   26 |   createLoadingComponent() {
>   27 |     return `<div>`Loading`</div>`;
>      |___________^
>   28 |   }
>   29 |   displayChildren() {
>   30 |     const { children } = this.props;`

It is not very well visible here but html tags are being reported as unexpected tokens.

**Expected outcome**
App starts displaying map

I would really love to test and use this library. Could you help with this error?

**Comment by zachmanring-natgeo** [comment]
I am having the same issue.. :/

**Comment by limistah** [comment]
I will look deeper into this.

**Comment by limistah** [comment]
Can you retry now, to see if I solve your issue before closing this issue?

Thank you.

**Comment by pawelkrystkiewicz** [comment]
It works now but I had to download the whole project from github because it's not available on npm.
And there is something wrong with the default example because it is really slow.
Thanks for taking the time for making it run though :)

**Comment by limistah** [comment]
Thank you for your feedback.
I have worked on the READ ME file to provide proper installation instruction.
