### ISSUE TITLE
Unwanted warning & console.log

### ISSUE THREAD

**Issue by subtirelumihail** [limistah/react-here-map#5]
There is a warning in the library
```
 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```
Which I think is related with this line: https://github.com/limistah/react-here-map/blob/master/src/components/Platform/index.js#L16

Also there is an unneccesary console.log that I think it can be removed

**Comment by limistah** [comment]
Hi @subtirelumihail, this library receives development during my free time. I will surely get to work on it very soon.

Thank you.

**Comment by limistah** [comment]
Hi, which section of the library are you working with?
