### ISSUE TITLE
Add mapEvents example to docs

### ISSUE THREAD

**Issue by pavinduLakshan** [limistah/react-here-map#6]
currently there is only mapOptions in the docs and there is no example to understand how to use mapEvents.

**Comment by TahinDani** [comment]
Yes, mapEvents documentation would be very helpful. I managed to handle some event, like tap or drag like this:
<HMap	
style={{height: '100vh'}}
mapOptions={{ center: { lat: 47.498056, lng: 19.04 }, zoom: 11 }}
mapEvents={{tap: (e) => {console.log('CLICKED')}}}
useEvents
>
It logs 'CLICKED' to the console but I can't access the event, so I don't know the coordinates of the point I clicked. How can I access it?

**Comment by limistah** [comment]
@TahinDani, I will give some updates later today.

Thanks for the nudge.

**Comment by limistah** [comment]
Sorry that it is coming too late, see it here: https://github.com/limistah/react-here-map#event-handling
